name: Daily YouTube Pipeline

on:
  schedule:
    - cron: "0 18 * * *"   # 12:00 AM IST
  workflow_dispatch:

env:
  NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

      # Clean workspace
      - name: Clean workspace
        run: rm -rf ./*

      # Checkout code
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install google-api-python-client psycopg2-binary python-dotenv

      - name: Run New Video Fetch
        run: python pipeline_fetch_videos_incremental.py

      - name: Run Daily Stats Fetch
        run: python pipeline_fetch_stats_incremental.py

      - name: Run Aggregations
        run: python pipeline_daily_aggregations.py
