name: Daily YouTube Pipeline

on:
  schedule:
    - cron: "0 18 * * *"   # 12:00 AM IST
  workflow_dispatch:

env:
  # Load from GitHub Secrets
  NEON_DB_URL_WRITE: ${{ secrets.NEON_DB_URL_WRITE }}              # <-- REQUIRED WRITE URL
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Clean workspace
        run: rm -rf ./*

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Debug secrets loaded
        run: |
          echo "NEON_DB_URL_WRITE exists? = ${{ secrets.NEON_DB_URL_WRITE != '' }}"
          echo "API key exists? = ${{ secrets.YOUTUBE_API_KEY != '' }}"

      - name: Run New Video Fetch
        run: python pipeline_fetch_videos_incremental.py

      - name: Run Daily Stats Fetch
        run: python pipeline_fetch_stats_incremental.py

      - name: Run Aggregations
        run: python pipeline_daily_aggregations.py
